cam_node:
    ros__parameters:
      video_device: "/dev/video0"
      framerate: 30.0
      frame_id: "camera"
      pixel_format: "yuyv"  # see usb_cam/supported_formats for list of supported formats
      av_device_format: "YUYV422"
      image_width: 640
      image_height: 480
      camera_name: "cam"
      autofocus: true
