joy_node:
  ros__parameters:
    device_id: 0
    deadzone: 0.05
    autorepeat_rate: 5.0 # Hz

teleop_node:
  ros__parameters:
    axis_linear:  # Left thumb stick vertical
      x: 1
    scale_linear:
      x: 0.2
    scale_linear_turbo:
      x: 2.0

    axis_angular:  # Left thumb stick horizontal
      yaw: 0
    scale_angular:
      yaw: 0.2
    scale_angular_turbo:
      yaw: 2.0

    enable_button: 4  # Left trigger button
    enable_turbo_button: 5  # Right trigger button

    require_enable_button: true

    inverted_reverse: true