rplidar:
  ros__parameters:
    serial_port: /dev/ttyUSB0
    serial_baudrate: 115200  # A1 / A2
    # 'serial_baudrate': 256000, # A3
    frame_id: lidar
    inverted: false
    angle_compensate: true